#!/usr/bin/env bash
#
# install.sh — install mayfly-agent as an unprivileged systemd service.
# Idempotent and safe to re-run. See deploy/README.md and ADR-0008/ADR-0009.
#
# Install ORDER: install mayfly-helper FIRST (from the mayfly-helper repository).
# The helper creates the shared `mayfly` user/group, the capability token
# (/etc/mayfly-agent/helper.token), and the managed SSH directories. This script
# installs only the unprivileged agent and expects the helper to be present.
#
# Usage:
#   sudo MAYFLY_SERVER_URL=https://mayfly.example.com \
#        MAYFLY_MACHINE_ID=$(hostnamectl --static) \
#        ./install.sh
#
# Optional env:
#   BINDIR                directory containing the built mayfly-agent (default: script dir)
#   MAYFLY_AGENT_BIN_DEST default /usr/local/bin/mayfly-agent
#   MAYFLY_SKIP_CHECKSUM  set to 1 to skip SHA256SUMS verification
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly BINDIR="${BINDIR:-$SCRIPT_DIR}"

readonly MAYFLY_USER="mayfly"
readonly MAYFLY_GROUP="mayfly"
readonly AGENT_BIN_DEST="${MAYFLY_AGENT_BIN_DEST:-/usr/local/bin/mayfly-agent}"
readonly CONFIG_DIR="/etc/mayfly-agent"
readonly CONFIG_FILE="$CONFIG_DIR/config.toml"
readonly TOKEN_FILE="$CONFIG_DIR/helper.token"
readonly STATE_DIR="/var/lib/mayfly"
readonly UNIT_DIR="/etc/systemd/system"

log()  { printf '[install-agent] %s\n' "$*" >&2; }
die()  { printf '[install-agent] ERROR: %s\n' "$*" >&2; exit 1; }

require_root() {
  [ "$(id -u)" -eq 0 ] || die "must run as root"
}

verify_platform() {
  [ "$(uname -s)" = "Linux" ] || die "mayfly-agent supports Linux only"
  case "$(uname -m)" in
    x86_64|aarch64|armv7l|armv6l) : ;;
    *) die "unsupported architecture: $(uname -m)" ;;
  esac
}

verify_dependencies() {
  local missing=()
  for cmd in systemctl getent install id; do
    command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
  done
  [ "${#missing[*]}" -eq 0 ] || die "missing required commands: ${missing[*]}"
}

verify_binary_present() {
  [ -f "$BINDIR/mayfly-agent" ] || die "mayfly-agent binary not found in $BINDIR"
}

verify_helper_present() {
  # The agent is non-functional for applies without the helper. Warn (not fail)
  # so the agent can still be installed/enrolled before the helper is online.
  if [ ! -e /usr/local/sbin/mayfly-helper ]; then
    log "WARNING: mayfly-helper not found at /usr/local/sbin/mayfly-helper"
    log "WARNING: install the mayfly-helper repository's package first"
  fi
  if [ ! -s "$TOKEN_FILE" ]; then
    log "WARNING: $TOKEN_FILE missing/empty; the helper installer generates it"
  fi
}

verify_checksum() {
  [ "${MAYFLY_SKIP_CHECKSUM:-0}" != "1" ] || { log "checksum verification skipped"; return; }
  if [ -f "$BINDIR/SHA256SUMS" ]; then
    command -v sha256sum >/dev/null 2>&1 || die "sha256sum required to verify SHA256SUMS"
    ( cd "$BINDIR" && sha256sum -c SHA256SUMS ) || die "checksum verification failed"
    log "checksum verification passed"
  else
    log "no SHA256SUMS found; skipping checksum verification"
  fi
}

ensure_user_and_group() {
  # Normally created by the helper installer; create-if-absent for robustness.
  getent group "$MAYFLY_GROUP" >/dev/null 2>&1 || { log "creating group $MAYFLY_GROUP"; groupadd --system "$MAYFLY_GROUP"; }
  if ! getent passwd "$MAYFLY_USER" >/dev/null 2>&1; then
    log "creating system user $MAYFLY_USER"
    useradd --system --gid "$MAYFLY_GROUP" --home-dir "$STATE_DIR" \
            --no-create-home --shell /usr/sbin/nologin "$MAYFLY_USER"
  fi
}

create_directories() {
  install -d -o root          -g "$MAYFLY_GROUP" -m 0750 "$CONFIG_DIR"
  install -d -o "$MAYFLY_USER" -g "$MAYFLY_GROUP" -m 0750 "$STATE_DIR"
}

install_binary() {
  log "installing mayfly-agent"
  install -o root -g root -m 0755 "$BINDIR/mayfly-agent" "$AGENT_BIN_DEST"
}

write_config_if_absent() {
  if [ -f "$CONFIG_FILE" ]; then
    log "config already present; leaving it unchanged"
    return
  fi
  [ -n "${MAYFLY_SERVER_URL:-}" ] || die "MAYFLY_SERVER_URL must be set to write an initial config"
  local machine_id="${MAYFLY_MACHINE_ID:-$(uname -n)}"
  log "writing initial config for $machine_id"
  cat > "$CONFIG_FILE" <<EOF
# Generated by install.sh. Edit to taste; restart mayfly-agent to apply.
server_url = "${MAYFLY_SERVER_URL}"
machine_id = "${machine_id}"
EOF
  chown root:"$MAYFLY_GROUP" "$CONFIG_FILE"
  chmod 0640 "$CONFIG_FILE"
}

install_unit() {
  log "installing systemd unit"
  install -o root -g root -m 0644 "$SCRIPT_DIR/systemd/mayfly-agent.service" "$UNIT_DIR/mayfly-agent.service"
  systemctl daemon-reload
}

start_service() {
  log "enabling and starting mayfly-agent"
  systemctl enable --now mayfly-agent.service
}

verify_installation() {
  log "verifying installation"
  systemctl is-active --quiet mayfly-agent.service || die "mayfly-agent failed to start"
  log "mayfly-agent is active"
}

main() {
  require_root
  verify_platform
  verify_dependencies
  verify_binary_present
  verify_helper_present
  verify_checksum
  ensure_user_and_group
  create_directories
  install_binary
  write_config_if_absent
  install_unit
  start_service
  verify_installation
  log "agent installation complete"
}

main "$@"
